INSERT IGNORE INTO `role` VALUES (3, 'ADMIN')
INSERT IGNORE INTO `role` VALUES (2, 'MOD')
INSERT IGNORE INTO `role` VALUES (1, 'USER')
INSERT IGNORE INTO `state` VALUES (1, 'ACTIVE')
INSERT IGNORE INTO `state` VALUES (2, 'ENDED')
INSERT IGNORE INTO `state` VALUES (3, 'CLOSED')
# ALTER TABLE `invitation` DROP `userid`