INSERT INTO `role` VALUES (3, 'ADMIN');
INSERT INTO `role` VALUES (2, 'MOD');
INSERT INTO `role` VALUES (1, 'USER');
INSERT INTO `state` VALUES (1, 'ACTIVE');
INSERT INTO `state` VALUES (2, 'ENDED');
INSERT INTO `state` VALUES (3, 'CLOSED');

